#include "LED_Cfg.h"



/**
 * @brief 
 * 
 * 
 * 
 * 
 *  MGPIO_PORTS_t MGPIO_portName;
    MGPIO_PIN_NUMBER_t MGPIO_pinNumber;
    MGPIO_PIN_STATE_t MGPIO_pinState;    
    MGPIO_PIN_MODE_t MGPIO_pinMode;
    MGPIO_OUT_SPEED_t MGPIO_outSpeed;
    MGPIO_OUT_TYPE_t MGPIO_outType;
    MGPIO_PULL_UP_DOWN_t MGPIO_pullUpDown;
    MGPIO_AF_t MGPIO_AFtype;
 * 
 */
MGPIO_PinConfig LED_Config[LED_NUMBER]=
{
    {MGPIO_GPIOG , MGPIO_PIN_13 , MGPIO_PIN_STATE_LOW ,MGPIO_MODE_OUTPUT,MGPIO_OUT_SPEED_MEDIUM ,(MGPIO_OUT_TYPE_t)NOTCARE, MGPIO_PULL_UP , (MGPIO_AF_t)NOTCARE},
    {MGPIO_GPIOD , MGPIO_PIN_12 , MGPIO_PIN_STATE_LOW ,MGPIO_MODE_OUTPUT,MGPIO_OUT_SPEED_MEDIUM ,(MGPIO_OUT_TYPE_t)NOTCARE, MGPIO_PULL_UP , (MGPIO_AF_t)NOTCARE},
    {MGPIO_GPIOD , MGPIO_PIN_14 , MGPIO_PIN_STATE_LOW ,MGPIO_MODE_OUTPUT,MGPIO_OUT_SPEED_MEDIUM ,(MGPIO_OUT_TYPE_t)NOTCARE, MGPIO_PULL_UP , (MGPIO_AF_t)NOTCARE}
};